services:
  postgres:
    image: postgres:16
    container_name: magicvs-postgres
    environment:
      POSTGRES_DB: magicvs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: magicvs-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: magicvs-backend
    environment:
      SPRING_PROFILES_ACTIVE: backend
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magicvs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SMTP_USER: "noreplymagicvs@gmail.com"
      SMTP_PASS: "qhxmzwbsoozavefg"
      SMTP_FROM: "noreplymagicvs@gmail.com"
      DECK_MIN_CARDS: ${DECK_MIN_CARDS:-60}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy

  data-ingestion-worker:
    build:
      context: ./backend
    container_name: magicvs-data-ingestion-worker
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: worker
      SPRING_MAIN_WEB_APPLICATION_TYPE: none
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magicvs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: magicvs-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
